Обработка 404 ошибок
spec-box/api pull request #11
Opened 2023-12-16 18:34 UTC by sr480

2023-12-16 18:52 UTC, sr480 commented on SpecBox.WebApi/Controllers/ExportController.cs
> +        var prj = await db.Projects.FirstOrDefaultAsync(p => p.Code == projectCode);
FirstOrDefault - производительнее, и у нас в БД констрэйнт на уникальность по полю код

2023-12-16 18:52 UTC, sr480 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +            return Problem("Feature duplicate found", "Feature", StatusCodes.Status500InternalServerError);
Если у нас дубликат фичи - то отвечаем 500й - это проблема сервера

2023-12-16 18:52 UTC, sr480 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +    public async Task<ActionResult<ProjectModel[]>> Projects()
ActionResult<FeatureModel> переделал везде на дженерик, так как тогда не требуется в атрибуте указывать тип возвращаемой сущности

2023-12-16 18:52 UTC, sr480 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +    [HttpGet("{project}/structure/{treeCode}")]
Добавил ручку для получения других деревьев

2023-12-16 18:52 UTC, sr480 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +    [HttpGet("{project}/trees")]
Добавил ручку для получения списка деревьев

2023-12-22 11:14 UTC, dima117 commented
содержимое PR не соответствует заголовку
- изменения, связанные с порядком сортировки
- дополнительные ручки, которые желательно сначала обсудить

2023-12-22 11:24 UTC, dima117 requested changes

2023-12-22 11:24 UTC, dima117 commented on SpecBox.WebApi/Controllers/ExportController.cs
> +        var prj = await db.Projects.FirstOrDefaultAsync(p => p.Code == projectCode);
тогда уж `First`, а не `firstOrDefault`

2023-12-22 11:24 UTC, dima117 commented on SpecBox.WebApi/Controllers/ExportController.cs
> +        if (prj == null) return NotFound();
по идее, это коды ответов протокола http, а не коды ответов предметной области

если передан id несуществующего проекта, то правильнее вернуть код `400 Bad request`, а  код `404 Not found` нужно возвращать в ответ на обращение к несуществующей ручке

2023-12-22 11:24 UTC, dima117 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +            return Problem("Feature duplicate found", "Feature", StatusCodes.Status500InternalServerError);
может быть, вместо оборачивания в try/catch сделать общий обработчик ошибок, который ловил бы все исключения и возвращал ошибку в единообразном формате?

2023-12-22 11:24 UTC, dima117 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +            return Problem("Feature duplicate found", "Feature", StatusCodes.Status500InternalServerError);
Предлагаю отлавливать исключения через `UseExceptionHandler` 
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-8.0#exception-handler-lambda

2024-02-04 13:57 UTC, closed without merging