поддержать загрузку и выгрузку зависимостей фичей друг от друга
spec-box/api pull request #17
Opened 2024-04-16 13:46 UTC by ilerik

2024-04-17 11:09 UTC, dima117 commented on SpecBox.Migrations/Migration_0016_ExportDependencies.cs
> +            new Column("DependencyFeatureId", DbType.Guid)
1. можешь написать подробнее, зачем убрал primary key?
2. опубликованные миграции нельзя менять. можно только добавлять следующие

2024-04-17 11:10 UTC, dima117 commented on SpecBox.Domain/Model/FeatureDependency.cs
> +    public Guid SourceFeatureId { get; set; }
здесь предлагаю добавить еще поля `SourceFeature` и `DependencyFeature` для автоматического приджоинивания таблиц с доп. полями

2024-04-17 11:17 UTC, dima117 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +                d => d.DependencyFeatureId,
по идее, вместо join нужно было сделать вложенную модель, а маппинг — через automapper

2024-04-17 11:17 UTC, dima117 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +                    AutomatedCount = 0,
нужно еще поле problemCount

2024-04-17 11:21 UTC, dima117 commented on SpecBox.WebApi/Model/Project/FeatureDependencyModel.cs
> +    public int AutomatedCount { get; set; }
по идее, поля с количеством — тоже обязательные

2024-04-18 06:10 UTC, dima117 commented on SpecBox.Domain/SpecBoxDbContext.cs
> +        modelBuilder.Entity<FeatureDependency>().HasNoKey();
для чего добавил HasNoKey?

2024-04-18 06:14 UTC, dima117 commented on SpecBox.WebApi/Controllers/ExportController.cs
> +                }
зачем дополнительные логи?

здесь написано "обрабатываем фичу ..." при том, что мы обрабатываем только её зависимости. там, где мы экспортируем саму фичу, логов нет

ну и на самом деле, мы здесь не обрабатываем данные, а в сыром виде кладем во временные таблицы, а фактическая обработка данных — на стороне БД, в хранимой процедуре, которая запускается в конце этой функции

2024-04-18 06:16 UTC, dima117 commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +            .ToList();
предлагаю здесь выбрать сразу только зависимые фичи 

```
var ds = db.FeatureDependencies
            .Where(d => d.SourceFeatureId == f.Id)
            .Select(t => t.DependencyFeature)
            .ToList();
```

2024-04-18 06:25 UTC, dima117 commented on SpecBox.WebApi/Model/Project/TreeNodeModel.cs
> +public class TreeNodeModel: NodeModel
кажется, не нужно делать такое наследование — нода в дереве и нода в графе — разные по смыслу сущности (например, в дереве могут отображаться не только фичи)

2024-04-18 06:26 UTC, dima117 requested changes
в целом всё очень круто, но нужно поправить замечания в комментариях

2024-04-18 10:53 UTC, ilerik commented on SpecBox.Domain/SpecBoxDbContext.cs
> +        modelBuilder.Entity<FeatureDependency>().HasNoKey();
RestError: System.InvalidOperationException: The entity type 'FeatureDependency' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943. вот такое ловлю

2024-04-18 10:54 UTC, ilerik commented on SpecBox.WebApi/Controllers/ExportController.cs
> +                }
убрал логи, согласен

2024-04-18 10:55 UTC, ilerik commented on SpecBox.WebApi/Controllers/ProjectController.cs
> +            // TO DO filter by projectCode (add ProjectId to FeatureDependencies?)
так и сделал, спасибо

2024-04-18 10:55 UTC, ilerik commented on SpecBox.WebApi/Model/Project/TreeNodeModel.cs
> +public class TreeNodeModel: NodeModel
убрал наследование,  согласен

2024-04-18 13:48 UTC, merged